accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import sign_up
app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup', sign_up)
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('learning_logs.urls')),
    path("accounts/", include('accounts.urls'))
]

learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, topic, topics, new_topic, new_entry, edit_entry

app_name = 'learning_logs'

urlpatterns = [
    path("", index),
    path("topics", topics),
    path("topic/<str:topic_text>/", topic),
    path("newtopic", new_topic),
    path("newentry/<str:topic_text>/", new_entry),
    path("editentry/<int:entry_id>/", edit_entry)
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User


class BaseModel():
    pass


class Topic(models.Model):
    text = models.TextField(max_length=200, unique=True, )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.text = self.text.lower()
        super().save()


class Entry(models.Model):
    date_added = models.DateTimeField(auto_now=True)
    text = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}"


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def sign_up(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('/')
    else:
        form = UserCreationForm()

    return render(request, "registration/signin.html", {'form': form})

learning_logs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound, HttpResponseForbidden
from .models import Topic, Entry, TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, "index.html")


@login_required
def topic(request, topic_text):
    user_topic = Topic.objects.filter(owner=request.user).filter(text=topic_text.lower()).first()

    if user_topic is None:
        return HttpResponseForbidden()

    context = {'topic': user_topic}
    return render(request, "topic.html", context)


@login_required
def topics(request):
    context = {'topics': Topic.objects.filter(owner=request.user).all()}
    return render(request, "topics.html", context)


@login_required
def new_topic(request):
    if request.method == "POST":
        form = TopicForm(data=request.POST)
        if form.is_valid():
            insert_topic = form.save(commit=False)
            insert_topic.owner = request.user
            insert_topic.save()
        return redirect("/topics")

    else:
        form = TopicForm()

    return render(request, "new_topic.html", {'form': form})


@login_required
def new_entry(request, topic_text):
    insert_topic = Topic.objects.filter(text=topic_text).filter(owner=request.user).first()

    if insert_topic is None:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = insert_topic
            new_entry.save()
        return redirect("/topic/" + str(insert_topic.text))

    else:
        form = TopicForm()

    return render(request, "new_entry.html", {'form': form, 'topic': insert_topic})


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.filter(id=entry_id).first()

    if entry is None:
        return HttpResponseNotFound()

    if entry.topic.owner != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            edit_entry = form.save(commit=False)
            edit_entry.topic = entry.topic
            edit_entry.save()
        return redirect("/topic/" + str(entry.topic))
    else:
        form = EntryForm(instance=entry)
        return render(request, "edit_entry.html", {'form': form, 'topic': entry.topic})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %} - Learning Logs</title>
</head>
<body>
<nav style="padding-left: 20px;" class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Learning Logs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/topics">Topics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/newtopic">New Topic</a>
            </li>
        </ul>
        <div style="width: 85%; justify-content: right" class="navbar-nav nav-brand">
            {% if user.is_authenticated %}
                <div class="nav-item">
                    <span style="margin-right: 5px; vertical-align: -webkit-baseline-middle">Hello, {{ user.username }}</span>
                </div>
                <div class="nav-item">
                    <a style="margin-left: 5px" class="btn btn-outline-primary"
                       href="/accounts/logout">Log Out</a>
                </div>
            {% else %}
                <div class="nav-item">
                    <a class="btn btn-primary" href="/accounts/login">Login</a>
                </div>
                <div class="nav-item">
                    <a style="margin-left: 5px" class="btn btn-outline-primary"
                       href="/accounts/signup">SignUp</a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>

<main class="row">
    <div class="container-fluid" style="padding: 30px">

        <div class="pb-2 mb-2 border-bottom">
            {% block header %}{% endblock header %}
        </div>

        {% block content %}{% endblock content %}
    </div>
</main>



<footer style="position:absolute;: relative; bottom: 10px; width: 100%">
    <p style="text-align: center; display: block; width: 100%">The Right to this Website is Copy Righted to Learning
        Logs</p>
</footer>
</body>
</html>

templates/edit_entry.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %} Edit Entry {% endblock title %}
{% block header %} <h2>Edit {{ topic.text }}'s Entry</h2> {% endblock header %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Edit Entry</button>
    </form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Index {% endblock title %}

{% block header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track your learning.</h1>
            <p class="lead">Make your own Learning Log, and keep a list of the
                topics you're learning about. Whenever you learn something new
                about a topic, make an entry summarizing what you've learned.</p>
            <a class="btn btn-primary btn-lg mt-1"
               href="/accounts/signup">Register &raquo;</a>
        </div>
    </div>
{% endblock header %}

templates/new_entry.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %} New Entry {% endblock title %}

{% block header %} <h2>New {{ topic.text }}'s Entry</h2> {% endblock header %}

{% block content %}
    <form action="/newentry/{{ topic.text }}/" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Insert</button>
    </form>
{% endblock content %}

templates/new_topic.html
{% extends 'base.html' %}

{% block title %} New Topic {% endblock title %}

{% block content %}
    <p>New Topic</p>
    <form action="/newtopic" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">Insert</button>
    </form>
{% endblock content %}

templates/topic.html
{% extends 'base.html' %}

{% block title %} {{ topic.text }} {% endblock title %}

{% block header %}
    <h2>{{ topic.text }}</h2> <a style="text-decoration: none" href="/newentry/{{ topic.text }}">New Entry</a>
{% endblock header %}

{% block content %}
    <ul>
        {% for entry in topic.entry_set.iterator %}
            <div class="card mb-3">
                <p style="font-size: 18px" class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
               <a style="font-size: 18px; text-decoration: none" href="/editentry/{{ entry.id }}">Edit</a>
            </p>
                <div class="card-body">{{ entry.text|linebreaks }}</div>
            </div>
        {% empty %}
            <p>There are No Entry Yet!</p>
        {% endfor %}

    </ul>
{% endblock content %}

templates/topics.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %} Topics {% endblock title %}

{% block header %} <h2>{{ user.username }}'s Topics</h2> {% endblock header %}

{% block content %}
    {% for item in topics %}
        <div class="card mb-3">
            <p style="font-size: 18px" class="card-header">
                {{ item.text }}
            </p>
            <div class="card-body">
                Created at {{ item.date_added|date:'M d, Y H:i' }} By {{ item.owner.username }}
                <br>
                <a style="margin-top: 10px" class="btn btn-primary" href="/topic/{{ item.text }}">View Entries</a>
            </div>

        </div>
    {% endfor %}
{% endblock content %}